
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxjmtkyikitaspzigofg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4am10a3lpa2l0YXNwemlnb2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODAzNTUsImV4cCI6MjA2MzQ1NjM1NX0.bxcAusb_sewavUgKf3rVCGMMaokZF_8DwKiEkUMWwTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    storageKey: 'supabase.auth.token',
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'prompt-library'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 2
    }
  }
});
